export interface Profile {
  profile_code?:string;
  profile_source?: string;
  profile_name?: string;
  gendar?: string;
  profile_type?: string;
  dob?: string;
  age: 0;
  caste_sect: string;
  subsect: string;
  add_subsect?: string;
  gothram: string;
  star_paadam: string;
  rasi: string;
  birth_time?: string;
  birth_place?: string;
  education?: string;
  occupation?: string;
  annual_income?: 0;
  job_location?: string;
  job_country?: string;
  height: string;
  weight?: string;
  father_detail?: string;
  mother_detail?: string;
  sibling_detail?: string;
  contact_relation?: string;
  primary_contact?: 0;
  secondary_contact?: 0;
  email_id?: string;
  brief_detail?: string;
  expectation?: string;
  other_info?: ' ';
  agree_inform_marriage?: string;
  agree_inform_exit?: string;
  self_declaration?: string;
  star: string;
  age_pref_from: 0;
  age_pref_to: 0;
  height_pref_from: string;
  height_pref_to: string;
  marriage_status?: string;
  profile_for?: string;
  created_by?: string;
  updated_by?: string;
  salary_currency?: string;
  father_name?: string;
  mother_name?: string;
  mother_tongue?: string;
  citizenship?: string;
  subscriber_id?: string;
  subscription_end_date?: Date;
  salary_preference:0
}
